# Write your MySQL query statement below
SELECT MAIN.NUM AS ConsecutiveNums
FROM LOGS MAIN
    JOIN LOGS SUB1 ON SUB1.ID = MAIN.ID + 1
    JOIN LOGS SUB2 ON SUB2.ID = MAIN.ID + 2
WHERE MAIN.NUM = SUB1.NUM AND MAIN.NUM = SUB2.NUM
GROUP BY MAIN.NUM